version: '3.8'

services:
  n1_app:
    container_name: n1_pr_app
    build:
      # context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
    networks:
      - n1_network

networks:
  n1_network: {}
